version: '3.7'

services:
  task-api:
    build: ./
    restart: unless-stopped
    volumes:
      - ./:/app:cached
      - /app/node_modules
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - tasks-bd
    environment:
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - API_PORT=${API_PORT}
  
  tasks-bd:
    image: mongo
    command: mongod --port ${MONGO_PORT}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - ./volumes/mongodb:/data/tasks-bd
